In [8]:
import numpy as np

In [9]:
a = np.random.randint(0,20,size=5)
a

array([ 5,  5, 19,  6, 12])

In [10]:
a[0] = 12
a

array([12,  5, 19,  6, 12])

In [11]:
a[-1] = 98
a

array([12,  5, 19,  6, 98])

In [12]:
m = np.random.randint(10,size=(3,3))
m

array([[8, 0, 3],
       [0, 2, 9],
       [2, 2, 9]])

In [14]:
m[0,2] # matris içerisinde istenilen konuma erişmek için

3

In [16]:
m[0,0] = 51 # matris içerisinde satır sütün bilgisi verilen yerin değerini değiştrimek için kullanılır.
m

array([[51,  0,  3],
       [ 0,  2,  9],
       [ 2,  2,  9]])