#### Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np

In [2]:
m = np.random.randint(0,30,size=(5,5))
m

array([[ 8, 24, 17, 12, 17],
       [15, 21, 20, 10, 15],
       [ 7,  8, 24, 15, 10],
       [ 9, 19,  0,  7, 27],
       [11, 18,  7, 28, 15]])

In [3]:
sub_m = m[:,1:4]
sub_m

array([[24, 17, 12],
       [21, 20, 10],
       [ 8, 24, 15],
       [19,  0,  7],
       [18,  7, 28]])

In [4]:
sub_m[0,0] = 99999
sub_m

array([[99999,    17,    12],
       [   21,    20,    10],
       [    8,    24,    15],
       [   19,     0,     7],
       [   18,     7,    28]])

In [5]:
m

array([[    8, 99999,    17,    12,    17],
       [   15,    21,    20,    10,    15],
       [    7,     8,    24,    15,    10],
       [    9,    19,     0,     7,    27],
       [   11,    18,     7,    28,    15]])

> Bir matrisin alt kümesi üzerinde bir değişiklik yaptığımızda bunun sadece alt küme üzerinde olmasını istiyorsak copy() metodunu kullanarak oluşturulan alt kümeyi ana kümeden bağımsız hale getiririz.


In [7]:
n = np.random.randint(0,80,size=(6,6))
n

array([[42, 43, 37, 13, 69,  8],
       [55, 41, 48, 17, 40, 16],
       [61, 75, 32, 45, 42, 36],
       [19, 13, 27, 21, 24, 55],
       [11, 19, 59, 60, 69, 64],
       [66, 58, 77, 71, 78,  6]])

In [8]:
sub_b = n[:,1:4].copy() # copy metodu ile n matrisinden bağımsız bir alt küme oluşturduk
sub_b

array([[43, 37, 13],
       [41, 48, 17],
       [75, 32, 45],
       [13, 27, 21],
       [19, 59, 60],
       [58, 77, 71]])

In [10]:
sub_b[0,0] = 588888
sub_b

array([[588888,     37,     13],
       [    41,     48,     17],
       [    75,     32,     45],
       [    13,     27,     21],
       [    19,     59,     60],
       [    58,     77,     71]])

In [11]:
n

array([[42, 43, 37, 13, 69,  8],
       [55, 41, 48, 17, 40, 16],
       [61, 75, 32, 45, 42, 36],
       [19, 13, 27, 21, 24, 55],
       [11, 19, 59, 60, 69, 64],
       [66, 58, 77, 71, 78,  6]])