#### Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np

In [2]:
m = np.random.randint(0,30,size=(5,5))
m

array([[22, 11,  7,  4, 26],
       [22, 10, 29, 10, 13],
       [18,  9,  3, 13,  0],
       [ 9,  8, 10,  3,  5],
       [ 0, 26, 10, 29, 27]])

In [4]:
sub_m = m[:,1:4]
sub_m

array([[11,  7,  4],
       [10, 29, 10],
       [ 9,  3, 13],
       [ 8, 10,  3],
       [26, 10, 29]])

In [8]:
sub_m[0,0] = 99999
sub_m

array([[99999,     7,     4],
       [   10,    29,    10],
       [    9,     3,    13],
       [    8,    10,     3],
       [   26,    10,    29]])

In [9]:
m

array([[   22, 99999,     7,     4,    26],
       [   22,    10,    29,    10,    13],
       [   18,     9,     3,    13,     0],
       [    9,     8,    10,     3,     5],
       [    0,    26,    10,    29,    27]])

> Bir matrisin alt kümesi üzerinde bir değişiklik yaptığımızda bunun sadece alt küme üzerinde olmasını istiyorsak copy() metodunu kullanarak oluşturulan alt kümeyi ana kümeden bağımsız hale getiririz.


In [12]:
n = np.random.randint(0,80,size=(6,6))
n

array([[14,  4,  1, 49, 40,  1],
       [33, 69, 79, 59, 30, 69],
       [46, 31, 50, 47, 78, 15],
       [62, 20, 22, 58, 54,  5],
       [73, 67,  5, 34, 50, 39],
       [23, 65, 55, 30, 31, 55]])

In [17]:
sub_b = n[:,1:4].copy() # copy metodu ile n matrisinden bağımsız bir alt küme oluşturduk
sub_b

array([[ 4,  1, 49],
       [69, 79, 59],
       [31, 50, 47],
       [20, 22, 58],
       [67,  5, 34],
       [65, 55, 30]])

In [15]:
sub_b[0,0] = 588888
sub_b

array([[588888,      1,     49],
       [    69,     79,     59],
       [    31,     50,     47],
       [    20,     22,     58],
       [    67,      5,     34],
       [    65,     55,     30]])

In [16]:
n

array([[14,  4,  1, 49, 40,  1],
       [33, 69, 79, 59, 30, 69],
       [46, 31, 50, 47, 78, 15],
       [62, 20, 22, 58, 54,  5],
       [73, 67,  5, 34, 50, 39],
       [23, 65, 55, 30, 31, 55]])