#### Array Birleştirme (Concatenation)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [6]:
np.concatenate([x,y]) # İki arrayi birleştirmek için concatenate metodu çalışır.

array([1, 2, 3, 4, 5, 6])

In [4]:
z = np.array([7,8,9])

In [5]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.array([[1,2,3],
         [4,5,6]])

In [10]:
np.concatenate([a,a]) # varsayılan olarak iki boyutlu iki arrayı satır bazın birleştirir.

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [11]:
np.concatenate([a,a],axis=1) # axis değeri 1 olduğu için sütun bazında bir birleştirme yapacaktır.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])