### Array Sıralama ###

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,4,6,7,3,9])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 6, 7, 9])

In [7]:
a = np.sort(v)
a

array([1, 2, 3, 4, 6, 7, 9])

### İki Boyutlu Array Sıralama ###

In [2]:
m = np.random.normal(20,5,(5,5))

In [3]:
np.sort(m,axis=1)

array([[11.77869265, 15.50384751, 17.46328675, 24.64058585, 27.36389494],
       [16.02474028, 19.68665504, 22.90745287, 23.53490393, 24.36940235],
       [22.17777297, 23.78423924, 23.876589  , 26.63835853, 29.37929991],
       [14.49029619, 16.11286909, 18.54738184, 21.53226541, 23.85333424],
       [15.25671813, 18.01711798, 19.85780473, 22.08447743, 23.23272555]])

In [4]:
np.sort(m,axis=0)

array([[18.54738184, 15.50384751, 14.49029619, 16.11286909, 11.77869265],
       [23.23272555, 21.53226541, 15.25671813, 17.46328675, 18.01711798],
       [24.36940235, 22.08447743, 16.02474028, 19.68665504, 22.90745287],
       [24.64058585, 23.53490393, 22.17777297, 19.85780473, 23.78423924],
       [29.37929991, 23.876589  , 27.36389494, 26.63835853, 23.85333424]])