#### Array Ayırma

In [3]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [5]:
np.split(x,[3,5]) # Ayrılma noktalarını vererek üç adet arraye böldük

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

In [6]:
a,b,c = np.split(x,[3,5])

### İki Boyutlu Ayırma ###

In [6]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.vsplit(m,[2]) # iki boyutlu matrislerde dikey bölme işlemi yapmak için kullanılır.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [16]:
ust,alt = np.vsplit(m,[2])

In [17]:
np.hsplit(m,[2]) # iki boyutlu matrislerde yatay bölme işlemi yapmak için kullanılır.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]