#### Array Alt Küme İşlemleri (Slicing)

In [1]:
import numpy as np

In [3]:
a = np.arange(1,20,2,dtype=int)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
a[0:3] 

array([1, 3, 5])

In [5]:
a[3:]

array([ 7,  9, 11, 13, 15, 17, 19])

In [6]:
a[:5]

array([1, 3, 5, 7, 9])

In [7]:
a[1::2] # Birinci elemandan başlar ve ikişer ikişer artar ve o indislerei gösterir.

array([ 3,  7, 11, 15, 19])

#### İki Boyutlu Slice İşlemleri

In [8]:
import numpy as np

In [9]:
m = np.random.randint(10,50,size=(5,5),dtype=int)
m

array([[12, 28, 20, 18, 22],
       [17, 27, 16, 14, 21],
       [36, 18, 24, 24, 44],
       [38, 34, 27, 22, 16],
       [14, 11, 23, 29, 21]])

In [14]:
m[:,0] # tüm satırların indisi 0 olan sütununu getir.

array([12, 17, 36, 38, 14])

In [15]:
m[:,4] # tüm satırların indisi 4 olan sütununu getir.

array([22, 21, 44, 16, 21])

In [16]:
m[1,:] # 1. satırın tüm sütunları  getir.

array([17, 27, 16, 14, 21])

In [18]:
m[1:4,1:4]

array([[27, 16, 14],
       [18, 24, 24],
       [34, 27, 22]])

In [19]:
m[:,1:3]

array([[28, 20],
       [27, 16],
       [18, 24],
       [34, 27],
       [11, 23]])