#### Array Alt Küme İşlemleri (Slicing)

In [1]:
import numpy as np

In [2]:
a = np.arange(1,20,2,dtype=int)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [4]:
a[0:3] 

array([1, 3, 5])

In [5]:
a[3:]

array([ 7,  9, 11, 13, 15, 17, 19])

In [6]:
a[:5]

array([1, 3, 5, 7, 9])

In [7]:
a[1::2] # Birinci elemandan başlar ve ikişer ikişer artar ve o indislerei gösterir.

array([ 3,  7, 11, 15, 19])

#### İki Boyutlu Slice İşlemleri

In [3]:
import numpy as np

In [5]:
m = np.random.randint(10,50,size=(5,5),dtype=int)
m

array([[23, 34, 24, 16, 20],
       [42, 42, 12, 38, 10],
       [20, 33, 17, 28, 44],
       [48, 42, 48, 34, 21],
       [31, 36, 14, 33, 42]])

In [6]:
m[:,0] # tüm satırların indisi 0 olan sütununu getir.

array([23, 42, 20, 48, 31])

In [7]:
m[:,4] # tüm satırların indisi 4 olan sütununu getir.

array([20, 10, 44, 21, 42])

In [8]:
m[1,:] # 1. satırın tüm sütunları  getir.

array([42, 42, 12, 38, 10])

In [18]:
m[1:4,1:4]

array([[27, 16, 14],
       [18, 24, 24],
       [34, 27, 22]])

In [19]:
m[:,1:3]

array([[28, 20],
       [27, 16],
       [18, 24],
       [34, 27],
       [11, 23]])