### Array Sıralama ###

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,4,6,7,3,9])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 6, 7, 9])

In [7]:
a = np.sort(v)
a

array([1, 2, 3, 4, 6, 7, 9])

### İki Boyutlu Array Sıralama ###

In [9]:
m = np.random.normal(20,5,(5,5))

In [10]:
np.sort(m,axis=1)

array([[12.13618767, 13.66199978, 15.24837783, 19.00464058, 20.51322435],
       [11.04936507, 18.26449939, 20.86292955, 23.92579753, 28.95229576],
       [19.64931904, 21.47830314, 22.56378691, 22.91408826, 25.71920046],
       [ 8.67114561, 12.41525217, 15.17303462, 22.99931577, 26.97403164],
       [15.1352385 , 17.1542069 , 19.09396779, 21.6305417 , 23.67477324]])

In [11]:
np.sort(m,axis=0)

array([[11.04936507, 18.26449939, 12.41525217,  8.67114561, 19.00464058],
       [12.13618767, 20.51322435, 13.66199978, 15.1352385 , 19.09396779],
       [15.17303462, 21.6305417 , 17.1542069 , 15.24837783, 25.71920046],
       [19.64931904, 22.56378691, 21.47830314, 20.86292955, 26.97403164],
       [23.67477324, 22.99931577, 23.92579753, 22.91408826, 28.95229576]])