#### Matematiksel İşlemler

In [1]:
import numpy as np

In [3]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
v - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [5]:
v ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [6]:
np.add(v, 12)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [7]:
np.subtract(v,9)

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [8]:
np.power(v,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
np.multiply(v,23)

array([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207])

In [10]:
np.divide(v,12)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ])

In [12]:
np.mod(v,2)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.absolute(np.array([-1,-2,-3,-35]))

array([ 1,  2,  3, 35])

In [14]:
np.cos(30)

0.15425144988758405

In [17]:
np.sin(90)

0.8939966636005579

In [18]:
np.tan(90)

-1.995200412208242

In [19]:
np.log(v)

C:\Users\musak\AppData\Local\Temp\ipykernel_7696\957696640.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(v)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])