#### Fancy Index ile Elemanlara Erişmek

In [1]:
import numpy as np

In [5]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
v[1]

3

In [7]:
v[5]

15

In [8]:
[v[1],v[2],v[6]]

[3, 6, 18]

In [9]:
indexes = [0,2,4,6,7]

In [12]:
v[indexes] # v arrayi içerisindeki indexes arrayi içerisindeki indexleri getirir.  

array([ 0,  6, 12, 18, 21])

> İki boyutta fancy Array

In [15]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [18]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
m[satir,sutun]

array([1, 5])

> Basit index ile fancy index

In [20]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
m[0,[1,2]]

array([1, 2])

> Slice ile fancy


In [22]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])