#### Koşullu Eleman İşlemleri Ve Matematiksel İşlemler

In [1]:
import numpy as np

In [3]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
v < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [6]:
v[v<3] #Fancy ile bu şekilde içeride 3den küçük elemanları yazdırabiliriz.

array([0, 1, 2])

In [7]:
v[v >= 3]

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
v / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [9]:
(v*5)/10

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
v**2 # Kare alma işlemi gerçekleşir.

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)