In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

Numpy aşağıdaki numpy dizisindeki tam sayıları da ondalıklı olarak kabul eder.

In [5]:
np.array([3.12,2,5,1.2,54.5])

array([ 3.12,  2.  ,  5.  ,  1.2 , 54.5 ])

İçi boş bir numpy dizisi oluşturmak için aşağıdaki gibi numpy zeros kullanılır.

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((3,3),dtype=int) # 3e 3lük bir 0 matrisi oluşturduk.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.ones((2,2),dtype=int) # 2ye 2lik bir 1 matrisi oluşturduk.

array([[1, 1],
       [1, 1]])

In [6]:
np.full((3,3),3) # istenilen değerde 3e 3lük bir matris oluşturmak için
#full kullanılır.

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [7]:
np.arange(0,100,2) # 0'dan 100'e kadar 2şer artan bir liste oluşturuyor.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [8]:
np.linspace(0,1,10) # 0 ile 1 arasında eşit aralıklı 10 adet sayı oluşturur.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(10,4,(3,4)) # ortalaması 10 standart sapması 4 olan 3'e 4lük bir matris oluşturduk.

array([[15.02574649, 10.82187503, 11.10547756, 12.58081193],
       [ 7.85646623,  6.12609262, 10.2482348 , 15.46208356],
       [11.51753116, 10.31196928, 20.39486901, 10.7384121 ]])

In [9]:
np.random.randint(0,10,(3,3)) # 0 ile 10 arasında sayı üreten 3e 3lük bir matris oluşturuyor.

array([[8, 0, 8],
       [8, 5, 8],
       [6, 8, 4]])